metaborg/jsglr

- org.spoofax.jsglr/src/org/spoofax/jsglr/client/SGLR.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/SGLRParseResult.java
The parser used to return a `SGLRParseResult` with old completion states even in case of failures.
The completion states are no longer used and bad error handling in the JSGLRI made it ignore parse errors.
Therefore we simplified the behaviour of the parser:
If parsing failed and we may try to recover, we do so.
If recovery fails, we throw a fatal exception.
If recovery succeeds, but the caller is not interested in the AST, we throw a fatal exception (after all, normal parsing failed).
If recovery claims to have succeeded, but the Disambiguator rejected the recovery, we throw a fatal exception.
We do this because normal parsing failed, and a rejected AST is a null value, so recovery actually didn't really succeed, it just claimed to.
Therefore, the result of parsing is either a fatal …
> Fix error behaviour of the parser.

- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/BaseBenchmark.java
- org.spoofax.jsglr2/pom.xml
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/util/Sdf2Table.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/util/WithGrammar.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/grammars/SumAmbiguousTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/grammars/SumNonAmbiguousTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/parser/CommentsTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/parser/IntersectionTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/parser/LookaheadTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/sdf/KernelTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/sdf/LexicalTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/sdf/ListsTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/sdf/LiteralsTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/sdf/OptionalsTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/sdf/PreferAvoidTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/tests/sdf/SdfSyntaxTest.java
After merging JSGLR2 [the build failed](http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/421/console) because it depended on `sdf2table` on the path. This PR copies the native `sdf2table` from `org.metaborg.spoofax.nativebundle` to the target directory of `org.metaborg.jsglr2` and sets it as executable. This `sdf2table` is then used for parse table generation for the tests instead of the local one. Fixed the problem for me after reproducing it locally by removing `sdf2table` from my path.
> Depend on sdf2table from org.metaborg.spoofax.nativebundle for JSGLR2 tests

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/util/WithGrammar.java
The [build still failed](http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/422/console) after #7. This PR makes sure the native `sdf2table` is only copied once to the target directory.
> Copy sdf2table to target directory only once

- org.spoofax.interpreter.library.jsglr/pom.xml
- org.spoofax.interpreter.library.jsglr/src/main/java/org/spoofax/interpreter/library/jsglr/JSGLRLibrary.java
- org.spoofax.interpreter.library.jsglr/src/main/java/org/spoofax/interpreter/library/jsglr/STRSGLR2_parse_implode_stream_pt.java
- org.spoofax.interpreter.library.jsglr/src/main/java/org/spoofax/interpreter/library/jsglr/STRSGLR_open_parse_table.java
- org.spoofax.interpreter.library.jsglr/src/main/java/org/spoofax/interpreter/library/jsglr/STRSGLR_parse_stream_pt.java
- org.spoofax.interpreter.library.jsglr/src/main/java/org/spoofax/interpreter/library/jsglr/STRSGLR_parse_string_pt.java
The idea is that the stratego compiler can try to use this new primitive and fall back on JSGLR1 with its error recovery on parse fail. See also the [use-jsglr2 branch in strategoxt](https://github.com/metaborg/strategoxt/commit/ac0275a7b1e37ad82de95f63e0f1da8bce147e85).
> Add JSGLR2 primitive

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/datadependent/DataDependentReduceManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/datadependent/DataDependentRuleNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/datadependent/DataDependentSymbolNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/elkhound/ElkhoundParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/elkhound/ElkhoundReduceManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveReduceManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveSymbolNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/IDerivation.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/ISymbolNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/ParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/basic/IBasicSymbolNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/basic/RuleNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/basic/SymbolNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/hybrid/Derivation.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/hybrid/ParseNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/Parser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/ReduceManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/Reducer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/ReducerSkipLayoutAndLexical.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/ReducerSkipLayoutAndLexicalAndRejects.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/ReducerSkipRejects.java
I found that the `getPreferredAvoidedDerivations` method for `SymbolNode`s and `hybrid.ParseNode` was duplicated four times. I've extracted this method to a `default` method as part of a new `ISymbolNode` interface. For the `DataDependent-`, `LayoutSensitive-`, and `SymbolNode` (which all use an `ArrayList` to store derivations), I've added an interface `IBasicSymbolNode` which can be seen as a trait that implements some of the methods of `ISymbolNode`, as they are all implemented in the same way throughout the three `*SymbolNode` classes anyway.
Related to this, the `Derivation` node classes (`*.RuleNode` and `hybrid.Derivation`) now have a method that returns the `productionType`, so that it can be used in the `getPreferredAvoidedDerivations` method in `ISymbolNode`. The type parameter …
> Refactor ParseForest node classes

- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/TokenDescriptor.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Result.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/ImplodeResult.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/NullParseForestStrategoImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizedTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/AbstractParse.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/IParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/Parser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/IParserObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/ParserLogObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/ParserObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/ParserVisualisationObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/result/ParseFailure.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/result/ParseResult.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/result/ParseSuccess.java
It used to be the case that the Parse (AbstractParse) state contained a
reference to a Tokens object, that would be passed along during
imploding.
Now, the Tokens object is only created inside the Imploder, as the
parser does not need to know anything about this Tokens object.
To do this, the IImploder interface has been updated to:
&nbsp;&nbsp;&nbsp;&nbsp;`implode(String input, String filename, ParseForest parseForest)`
Related to this, also the Result classes have been decoupled.
ParseResult and ImplodeResult now only have one type parameter*,
as the first only needs to know the type of the ParseForest,
while the second only needs to know the type of the AbstractSyntaxTree.
The class JSGLR2Result is now constructed as the combination of a
ParseResult and an ImplodeResult, rather than …
> Decouple Parse state from Imploder state

- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/BenchmarkParserObserver.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/datastructures/JSGLR2ActiveStacksBenchmark.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/datastructures/JSGLR2ForShifterBenchmark.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/ParserMeasureObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/datadependent/DataDependentParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/basic/BasicParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/hybrid/HybridParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/IParserObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/ParserLogObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/ParserObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/ParserVisualisationObserver.java
- The ParserObserver now resets id maps and counts when starting parse
- Fix type generics for some of the benchmarking observers
- Change createDerivation to accept derivation node instead of number
- Store derivation nodes in a new id map
- Uses the same id space as parse nodes, because they are in one tree
in the visualisation
> Fix observers

- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/Sdf3ToParseTable.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/testset/TestSetReader.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
I resolved the warning about the `DummyEditorRegistry` by binding the `NullEditorRegistry`. Besides that, I've done some small refactorings regarding inlining of variables.
> Refactor integrationtest

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/actions/ActionsFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/datadependent/DataDependentParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TermTreeFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/ParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/basic/BasicParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/empty/NullParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parseforest/hybrid/HybridParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/ReduceManagerFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/Reducer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/ReducerSkipLayoutAndLexical.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/ReducerSkipLayoutAndLexicalAndRejects.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/reducing/ReducerSkipRejects.java
This will be useful for incremental parsing, as the state of the stack will be saved in the parse nodes.
The `LayoutSensitiveParseForestManager` can still use the stack position as `beginPosition`, as it used to.
Other `ParseForestManager`s are not affected (besides method signature changes), as they do not use the `Position` anymore.
> Pass StackNode to ParseForestManager instead of just Position

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/Position.java
I've found the source of the quadratic time complexity of the Imploder. For every lexical, `Position.step` was called, which called `Position.atEnd`, which splits the entire input string on newlines. With a source file of thousands of lines, this becomes a bit expensive, taking O(n) time for each of the O(n) tokens.
I've changed the `step` method to only step over `width` characters.
> Optimize Position.step

- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2Benchmark.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkParseTable.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkParsing.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkParsingAndImploding.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/IntegrationVariant.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/ParseTableVariant.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/Sdf3ToParseTable.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/WithParseTable.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/WithParseTableFromTerm.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/testset/TestSetReader.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTestWithParseTableFromTermWithJSGLR1.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTestWithSdf3ParseTables.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Variants.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/ImploderVariant.java
- `JSGLR2Variants.Variant` has been moved to the integration package and renamed to `IntegrationVariant`
- The method `testVariants` is now a member of `IntegrationVariant`
- `JSGLR2Variants.ParseTableVariant` has been moved to the integration package as well
- Added `ImploderVariant`
- Added `JSGLR2Variants.Variant`, which combines a `ParserVariant` with an `ImploderVariant`
I've made sure that all methods inside `JSGLR2` and `JSGLR2Variants` do not use anything from the integration project.
> Refactor JSGLR2Variants and add ImploderVariant

- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/grammars/RejectTest.java
Hotfix to the master branch, as apparently the build script is currently failing. Thanks to @Taeir for pointing that out to me :slightly_smiling_face: 
Both the original parser (`ParseForestRepresentation:Hybrid`) and the incremental parser (`ParseForestRepresentation:Incremental`) fail at the reject tests. The odd thing is that these tests just pass when running the integration tests separately...
I suggest we just ignore these tests for now, as they were before I added my incremental parser.
<details>
<summary>Excerpt of the build log</summary>
Only the interesting bits:
```
(...)
846.407251 [INFO] Running org.spoofax.jsglr2.integrationtest.grammars.RejectTest
(...)
848.229541 [ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 1, Time elapsed: 1.817 s <<< FAILURE! - in …
```
> Ignore flaky tests

- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2Benchmark.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/datastructures/JSGLR2DataStructureBenchmark.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/ParsingMeasurements.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Implementation.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Variants.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/IObservableParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/IParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/Parser.java
For the public `JSGLR2` interface and the semi-public `IParser` interface, I've removed type parameters that do not need to be known by users of these interfaces.
E.g. in Spoofax Core, we don't care anymore which type of parse forests are being used. (see also https://github.com/metaborg/spoofax/pull/45).
In the `IParser` interface, the type of the stack nodes was only necessary for the `observing` method. This method has been pushed down to a new interface (`IObservableParser`), which includes both the `observing` method and a type parameter for the stack nodes. The base parser now implements `IObservableParser` instead of `IParser`.
In the `JSGLR2` interface, the type of the parse forest is only useful for internal use. Therefore, a new class `JSGLR2Implementation` has been created that …
> Remove type parameters that are not needed for users

- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/AbstractTokenizer.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/ITokens.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/Tokenizer.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/TreeBuilder.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/incremental/IncrementalSGLR.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/tokens/Tokens.java
Once I noticed, I could not un-see it. :see_no_evil: 
This rename also causes one change in Spoofax core (see metaborg/spoofax#47).
> Change isAmbigous to isAmbiguous

- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/TermTreeFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TermTreeFactory.java
A small change to the imploder that puts imploder attachments on sublists.
Currently NaBL2 error messages can get lost if they are attached to lists
without origin information. Adding imploder attachments on sublists as well
seems to solve that problem.
The change does the following:
- The imploder attachment for the top-level element stays the same as it was.
- For sublists, it uses the left token of the first child, and the right token
of the whole list.
- For the empty sublist, it uses the right token of the last child as a left
token, and the right token of the whole list. Note that this case is only for
empty sublists, which means there always was a previous child for the last
right token. This logic is not used if the top-level list is empty, in which
case the left and right token …
> Put imploder attachments on sublists.

- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2Benchmark.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkParseTable.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkParsing.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkParsingAndImploding.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/IntegrationVariant.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Implementation.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Result.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Variants.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/ITokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/ImploderVariant.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeStrategoTermImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/NullStrategoImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/StrategoTermImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizeResult.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizedTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/incremental/IncrementalStrategoTermImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/incremental/IncrementalTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/tokens/NullTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/tokens/TokenizerVariant.java
This PR adds a separate enum `TokenizerVariant`, instead of having the different tokenizer variants hidden in the imploder variants.
This will allow for separate benchmarking for imploding and tokenizing.
Old situation:
- `IImploder<ParseForest, Tree>` returned an `ImplodeResult<Tree>`, containing a `Tokens` object and a `Tree` object (the AST).
- The `TokenizedTreeImploder` could directly return an `ImplodeResult<Tree>`, as it built the AST and tokens at the same time.
- The separated imploders and tokenizers had to be composed together in order to make this work.
New situation:
- The class `ImplodeResult<Tree>` has been renamed to `TokenizeResult<Tree>`, as the imploder does not necessarily return a `Tokens` object anymore.
- `IImploder<ParseForest, ImplodeResult>` returns an …
> Tokenizer variant

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParse.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/EagerLookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/LazyLookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/parseforest/IncrementalParseForest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/lookaheadstack/AbstractLookaheadStackTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/lookaheadstack/EagerLookaheadStackTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/lookaheadstack/LazyLookaheadStackTest.java
While benchmarking, I found out that the current implementation of the lookahead stack is very memory-inefficient. It used to walk the parse forest nodes that are on the stack in order to calculate the lookahead character(s), using `StringBuilder`s to which the contents of the leaves (`CharacterNode`s) of the forests.
Now, the lookahead stacks make use of the input string. The lookahead stacks will keep track of their current position in the input/forest, making the querying of the current character a matter of calling `charAt`, and querying of lookahead a matter of calling `substring`.
This also finishes up the implementation for the `LazyLookaheadStack`, because I never took the effort to walk this more complicated stack in order to calculate the lookahead. Now, this can be done using …
> Optimize lookahead stack

- org.spoofax.jsglr2/pom.xml
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/EditorUpdate.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParse.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/JGitHistogramDiff.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/ProcessUpdates.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/SingleDiff.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/DiffAlgorithm.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/Edit.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/EditList.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/HashedSequence.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/HashedSequenceComparator.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/HashedSequencePair.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/HistogramDiff.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/HistogramDiffIndex.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/IntList.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/LongList.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/LowLevelDiffAlgorithm.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/MyersDiff.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/RawCharUtil.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/RawText.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/RawTextComparator.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/Sequence.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/SequenceComparator.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/Subsequence.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/SubsequenceComparator.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/diff/JGitHistogramDiffTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/diff/ProcessUpdatesTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/diff/SingleDiffTest.java
(I couldn't re-open #42 because I have rebased this branch.)
This PR improves the calculating of the text diff and applying that to the parse forest in several ways.
- Processing `EditorUpdate`s has been moved from several methods in `IncrementalParse` to its own class called `ProcessUpdates`.
- A new diffing algorithm has been added, taken from [JGit](http://download.eclipse.org/jgit/site/5.3.0.201903130848-r/org.eclipse.jgit/apidocs/index.html?org/eclipse/jgit/diff/HistogramDiff.html).
- This diffing algorithm allows multiple changes in one file to be identified.
- A small adapter has been written around this algorithm to make it return a list of `EditorUpdate`s.
- **New compared to #42:** the code of JGit has been copied into a sub-package of this repository to avoid having an extra …
> Improve diffing

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeStrategoTermImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/StrategoTermImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/incremental/IIncrementalImplodeInputFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/incremental/IncrementalImplodeInput.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/incremental/IncrementalStrategoTermImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/incremental/IncrementalTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/input/IImplodeInputFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/input/ImplodeInput.java
Instead of adding an extra parameter to `implodeParseNode` and `implodeDerivation`, the first input parameter is now a generic object that can contain whichever input needs to be passed to these methods.
For the regular imploder, this object (of class `ImplodeInput`) will only contain the input string. For the incremental imploder, this object (of class `IncrementalImplodeInput`) will also contain the `WeakHashMap` that is used as cache.
To properly override `implodeParseNode` in `IncrementalTreeImploder`, the type of the input object needs to be a type parameter of the class. Because of this, there needs to be a factory that creates the input object.
> Reduce duplicate code in incremental imploder

- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/ParseTableVariant.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTestWithSdf3ParseTables.java
In the integration tests, quite some time was lost by generating parse tables that had already been generated before. Therefore, I have added a parse table table (pun intended) that stores for every `(sdf3Resource, parseTableVariant)` pair the parse table that has been generated.
On my machine, this improves the run time of the integration tests from 38 seconds to 23 seconds. :smile::rocket: 
Before:
After:
Note: the parse table variant is currently not yet used in parse table generation. Because this may be the case later, I've still added it as key to the table.
> Make sure parse tables are only created once in integration test

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/AbstractLookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/EagerLookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/LazyLookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/ParserLogObserver.java
There was some duplicate code in the different types of `LookaheadStack`. I've created a common abstract super-class to pull the duplicate code to.
As an added bonus, I've fixed a small typo.
> Extract duplicate code to AbstractLookaheadStack

- org.spoofax.jsglr/src/org/spoofax/jsglr/client/IKeywordRecognizer.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/IRecoveryResult.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/editregion/detection/LCSCommand.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/IToken.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/ITokens.java
Just a fix for an IntelliJ code inspection.
Immediately ran the auto-formatter for `IToken` and `ITokens`, while I was there anyway.
> Remove redundant access modifiers in interfaces

- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTestWithLayoutSensitiveSdf3ParseTables.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/grammars/LayoutSensitiveDisambiguationTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutConstraintEvaluator.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveDerivation.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveParseNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveReduceManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/NoValueLayoutException.java
Removing obsolete code and refactoring in the layout-sensitive parsing implementation and tests. For testing, I added that tests check that inputs that are discarded due to layout-constraints are valid when parsed without layout-sensitivity enabled.
> Refactor layout-sensitive parsing implementation and tests

- org.spoofax.jsglr2.cli/pom.xml
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/JSGLR2CLI.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/WrappedException.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/output/DefaultOutputProcessor.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/output/IOutputProcessor.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/output/dot/DotOutputProcessor.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/output/dot/DotVisualisationParserObserver.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/output/dot/ParseForestDotVisualisationParserObserver.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/output/dot/StackDotVisualisationParserObserver.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/parserbuilder/ParseTableOptions.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/parserbuilder/ParserBuilder.java
- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/parserbuilder/SpoofaxLanguageFinder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Variant.java
I've done a major refactoring to the way that the CLI works. Most notable changes:
- The output options are no longer hardcoded in the CLI class, but are moved to a separate class and can be swapped in or out by setting `JSGLR2CLI.outputProcessor`. The output processor has to implement a couple of methods that check whether the config is correct (`checkAllowed`), whether the parser should receive observers (`observers`), and four methods for processing the parse/implode result/failure.
- The CLI can now load an SDF file by peeking in the `*.spoofax-language` file for the language identifier given as `--language` option.
- This used to be a hidden feature in `--parseTable`, but for extensibility it's better to separate these options.
- The location of the local Maven repository is get via …
> Extensible CLI

- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/TokenDescriptor.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/grammars/TokenizationTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/treefactory/TokenizedTermTreeFactory.java
During the development of the [Spoofax Pygments Lexer](https://github.com/ChielBruin/spoofax-latex-tools), @ChielBruin and I discovered some inconsistencies in how `ImploderAttachment`s stored the sort of an AST node. A couple of examples:
- JSGLR1 used to store the sort of a lexical AST term, but JSGLR2 always stored `null` as sort in this case. This broke ESV coloring that depended on this lexical sort (see 085ea3b).
- Calling `getSort` on a list/optional/etc symbol from a parse table taken directly from SDF3 generation returned `null`, but calling `getSort` on the same sort of a serialized-and-deserialized parse table would return the base sort (see metaborg/sdf#32 for more details; also, the new integration tests rely on this PR).
- Other small inconsistencies between a couple of the …
> Consistent tokens

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/AbstractLookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/EagerLookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/ILookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/LazyLookaheadStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/lookaheadstack/LinkedLookaheadStack.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/lookaheadstack/AbstractLookaheadStackTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/lookaheadstack/LinkedLookaheadStackTest.java
This PR adds support for cloning a lookahead stack, so that it can be stored in a choice point and used when jumping back to this point. If the implementation of parsing with recovery somehow requires that choice points can be jumped back to multiple times, then the lookahead stack should also be cloned when restoring it from a choice point, in order to not change the stored lookahead stack.
The `LinkedLookaheadStack` acts like the `EagerLookaheadStack` (in that it explicitly pushes all children of a broken-down node to the stack), but the difference is that the stack is now implemented using immutable linked-together nodes. This means that cloning the lookahead stack to store it in a choice point becomes much less expensive.
Note that this implementation can later be replaced with …
> Add LinkedLookaheadStack and make ILookaheadStack clonable

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IIncrementalParseState.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParseState.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/parseforest/IncrementalCharacterNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/parseforest/IncrementalDerivation.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/parseforest/IncrementalParseForest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/parseforest/IncrementalParseForestManager.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/parseforest/IncrementalParseNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/recoveryincremental/RecoveryIncrementalParseState.java
This should make the meaning of the method more clear.
In addition to this, the `state` field has been moved from `IncrementalDerivation` to `IncrementalParseNode`, which removes a layer of indirection in most cases.
The `state` field is set to `NO_STATE` when a new derivation is added, following Wagner's algorithm more closely.
To make the algorithm even more understandable, `IncrementalParseNode`s now have a method named `isReusable` and no longer expose the `state` field directly.
> Rename IIncrementalParseState.isMultipleStates to newParseNodesAreReusable

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeTokenizer.java
@jasperdenkers to fix your WIP commit 09c474c91486f4ddbffbb7cbb2be26881f7c3ccd :slightly_smiling_face: 
The problem was that you needed the `startPosition` to create the message, as you did in [line 113 of `TreeTokenizer`](https://github.com/metaborg/jsglr/pull/65/files#diff-77ccac298ad768082f12c80edc422128R113), but the `currentPos` variable in the iterative tokenizer corresponded to the `pivotPosition` instead of the `startPosition`. I fixed this by also saving the `startPosition`s on a stack.
> Fix messages generated by IterativeTreeTokenizer

- org.spoofax.jsglr2.cli/src/main/java/org/spoofax/jsglr2/cli/JSGLR2CLI.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/parsing/ParsingMeasurements.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/ProcessUpdates.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/EagerIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/LazyIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/LinkedIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/IParser.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/incremental/diff/ProcessUpdatesTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/inputstack/incremental/AbstractIncrementalInputStackTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/inputstack/incremental/EagerIncrementalInputStackTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/inputstack/incremental/LazyIncrementalInputStackTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/inputstack/incremental/LinkedIncrementalInputStackTest.java
Fixing a woopsie :innocent: 
In the incremental tests, `variant.jsglr2()` was called for every input string. Calling this method builds a new `JGSLR2Implementation` object with new caches, i.e. the previous results were never reused. This is fixed in a46bebe by extracting a variable that holds the `JSGLR2` instance.
Other than that, the commits should speak for themselves :slightly_smiling_face:
> Incremental optimized parse forest fix

- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/IntegrationVariant.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/integration/ParseTableVariant.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Variant.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/ParserVariant.java
Replacing "standard" variants with `_`. Now I can actually see which variants are failing, because the full name never fits on my screen :joy:
> Make the parser variants descriptions shorter

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/AbstractTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeStrategoTermTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/StrategoTermTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizedTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/treefactory/TokenizedTermTreeFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/Position.java
Ports the behaviours that were added to the combined imploder-tokenizer in #37 and #39 to the separate imploders/tokenizers, plus some minor other changes (see commit log).
> Consistent imploders

- org.spoofax.jsglr2.integration/src/main/resources/grammars/tokenization.sdf3
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/TokenizationTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeTokenizer.java
In the added test for an empty list, the separated imploders/tokenizers would throw `NullPointerException`s in `configureInjection` because there would be `null` tokens on their subtrees, or in other words, there would be no `ImploderAttachment` to configure the injection for.
This commit makes sure that every context-free subtree has tokens.
For empty subtrees, the `parentLeftToken` is used.
This behaviour matches the changes in 130eef6484c04aa05e4f04be968eb06f9f0f4c3d.
> Fix imploder attachments for injections on empty trees

- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
Fixes a small issue where resource paths in the integration tests couldn't be parsed on Windows.
> Fix incorrect resource path on Windows.

- org.spoofax.jsglr2.integration/src/main/resources/grammars/legacy-cc-in-kernel.sdf3
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/LegacyCharacterClassInKernelTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/JSGLR2Variant.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizedTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/incremental/IncrementalStrategoTermImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/incremental/IncrementalTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/treefactory/ITokenizedTreeFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/treefactory/ITreeFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/treefactory/StrategoTermTreeFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/treefactory/TokenizedTermTreeFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/tokens/Tokens.java
The recursive method `implodeParseNode` now accepts any `ParseForest` (i.e. including `CharacterNode`s), instead of just `ParseNode`s. This fixes the `ClassCastException` that used to be thrown when parsing a grammar production that used "naked" (not wrapped in a lexical rule) character classes in kernel syntax. Examples of such a grammar rule are found [here](https://github.com/webdsl/webdsl/blob/master/src/org/webdsl/dsl/syntax/languages/java-15/lexical/literals/EscapeSequences.sdf#L20).
JSGLR1 handles this by imploding the character to a `StrategoInt` (which IMO is ugly, but hey, legacy code :sweat_smile:). The JSGLR2 imploders now do this as well. This behaviour is verified with an added integration test that tests both versions of JSGLR.
> Imploder fix: allow character class in kernel syntax

- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/EmojiTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/JGitHistogramDiff.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/ProcessUpdates.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/RawCharUtil.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/RawText.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/diff/jgit/RawTextComparator.java
This PR fixes some bugs related to the combination of incremental + Unicode:
- The positions reported by the diff algorithm were in terms of offset in the UTF-8-encoded string, instead of offset in the UTF-16. This caused a mismatch in the reported offset when the string contained Unicode chars. This is fixed in 5fd9f1c by changing the diff algorithm to use 16-bit `char` instead of the original 8-bit `byte`.
- Fix `ProcessUpdates` for characters wider than 1 (8c66401). The tree updating algorithm assumed that all characters would have width 1, but this is no longer the case: Unicode chars above value 65535 have a width of 2 (because they are stored in a Java string using two UTF-16 elements).
I ran the full build locally, and it passes :slightly_smiling_face:
> Unicode diff bug

- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/Token.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeStrategoTermTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/StrategoTermTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizedTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeTokenizer.java
This fixes the following bugs related to consistent tokenization between the different variants
- Make `Token`s calculate `getEndColumn` correctly with wide Unicode characters (all tokenizer variants)
- Recursive/iterative tokenizers: add attachments to children of `amb`/`meta-var` (for recursive and iterative tokenizer variants)
- Reset `pivotPosition` when moving to next child of ambiguous subtree (for recursive and iterative tokenizer variants)
- Set `leftToken` and `rightToken` for character nodes (all tokenizer variants)
> Tokenizer consistency

- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/Token.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/imploder/TreeBuilder.java
- org.spoofax.jsglr2.integration/src/main/resources/grammars/emoji.sdf3
- org.spoofax.jsglr2.integration/src/main/resources/grammars/empty-list-ambiguous.sdf3
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/TokenDescriptor.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/disambiguation/EmptyListAmbiguousTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/EmojiTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/OptionalsTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/TokenizationTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/AbstractTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizedTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/tokens/Tokens.java
The tokenizers will now create empty (i.e. start offset == end ofset) tokens for AST nodes that have no corresponding region in the input string, instead of (ab)using the `parentLeftToken` for this. This causes the token stream to contain empty tokens, which can be safely ignored. Since these empty tokens have kind `TK_NO_TOKEN_KIND`, they are already ignored the `CategorizerService` that facilitates syntax highlighting. Also, error messages displayed on these empty tokens seem to work out:
<details>
<summary>Warning displayed on a `None` AST node that has no corresponding region in the input</summary>
</details>
To make sure that all tokenizer variants produce the same imploder attachments and tokens, I've extended `BaseTest.testSuccess` with a check that walks over the entire AST to …
> Empty tokens

- org.spoofax.jsglr2.integration/src/main/resources/grammars/kernel-string.sdf3
- org.spoofax.jsglr2.integration/src/main/resources/grammars/kernel-syntax.sdf3
- org.spoofax.jsglr2.integration/src/main/resources/grammars/sdf-syntax.sdf3
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/KernelStringTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/KernelSyntaxTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/IterativeTreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizedTreeImploder.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TreeTokenizer.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/tokens/treeshaped/AbstractTreeShapedTokenizer.java
Figured out that this was broken while I was writing down the tokenization algorithm in my thesis report. I realized that it was silly that empty (i.e. `tree.width == 0`), non-context-free parse nodes would always result in `null` tokens. After all, empty tokens are considered supported since #77, and I could come up with a scenario where an empty token would be required for lexical parse node.
I created a test with this scenario, see `KernelStringTest.java` and `kernel-string.sdf3`. Basically, the Stratego term `""` requires a token, and the most logical thing to do in this case is to create an empty token, just like we did for empty lists in #77. Note that the tokens for the quotation marks (before and after the empty token) are already attached to the context-free `String(...)` AST …
> Allow 0-width tokens on lexical AST nodes

- org.spoofax.jsglr/src/org/spoofax/jsglr/client/ParseTable.java
- org.spoofax.jsglr/src/org/spoofax/jsglr/client/ProductionAttributes.java
- org.spoofax.jsglr2.integration/src/main/resources/grammars/expressions-non-assoc.sdf3
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/MessageDescriptor.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/CyclesTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/NonAssocMessagesTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/features/ParseFailureMessagesTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/recovery/RecoveryInsertionMessagesTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/recovery/RecoveryLexicalHiddenInsertionMessagesTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/recovery/RecoveryLexicalInsertionMessagesTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/recovery/RecoveryMessagesTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/recovery/RecoveryPermissiveLiteralTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/recovery/RecoveryWaterMessagesTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/messages/Message.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/messages/SourceRegion.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/NonAssocDetector.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/Parser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/result/ParseFailureCause.java
To be merged together with metaborg/sdf#50 and metaborg/spoofax#73. Recommended order of reading: SDF, JSGLR, Spoofax.
The parse table reader has been adapted to recognize the new `assoc-with` attributes on productions in the ATerm parse table format, see [ParseTable.java:404-422](https://github.com/metaborg/jsglr/compare/master...mpsijm:non-assoc-warnings?expand=1#diff-e18e1a7cb4a99fd9061082e6b2a315e4R404-R422). The option to retrieve the global list of non-associative pairs from the parse table generator has been removed.
Because I didn't want to change how non-assoc error messages are generated in `JSGLR1I` (see metaborg/spoofax#73), I decided to rewrite the "for each production, a list of production labels" approach back into the "global table with mutually non-associative pairs of …
> Errors for non-assoc by storing extra data in parse table

- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/IParserObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/LogParserObserver.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/RegisteringParserObserver.java
No more `UnsupportedOperationException`s in `IIncrementalInputStack.getChar()` :smile: 
As a bonus, I've added a log for when parse nodes are broken down, to make the incremental parse log slightly more readable :slightly_smiling_face:
> Fix logger for incremental parser

- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/messages/Category.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/messages/Message.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/AmbiguityDetector.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/CycleDetector.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/NonAssocDetector.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/result/ParseFailureCause.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/recovery/RecoveryMessages.java
When message categories were added in a41a71741a1d052326431284675ce8ea3b801c2f, I noticed that the severity of messages contains a strong link with their category. I therefore decided to add the severity of a category as a field to the `Category` enum. This simplifies the creation of messages.
This is all under the assumption that every message category always has exactly one severity. If you think there could be a case where this is not true, please discuss :slightly_smiling_face:
> Improve messages

- org.spoofax.jsglr/src/org/spoofax/jsglr/client/ParseTable.java
Open streams can cause file locking issues on Windows, and other
streams not opening to the file.
The constructors where I made changes don't really make sense to me. I
think maybe some was overzealous in removing code duplication between
two constructors? `FileContent.getInputStream` never returns null anyway.
This change does have a semantic difference in that previously the file
was attempted to be opened, so an Exception from that would previously
be triggered and isn't now. I assumed that wasn't the reason for opening
stream.
> Fixes dangling open stream

- org.spoofax.jsglr2.benchmark/pom.xml
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkIncremental.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkIncrementalExternal.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkIncrementalParsing.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/util/JSGLR2MultiParser.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/util/JSGLR2PersistentCache.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/treesitter/TreeSitterBenchmark.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/treesitter/TreeSitterBenchmarkIncremental.java
- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/treesitter/TreeSitterParser.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/testset/TestSet.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/testset/TestSetIncrementalMultipleInput.java
- org.spoofax.jsglr2.integration/src/main/java/org/spoofax/jsglr2/testset/TestSetInput.java
To be merged together with metaborg/jsglr2evaluation#4.
To run the TreeSitter benchmarks, you'll have to manually run `mvn install` for https://github.com/mpsijm/java-tree-sitter before building the benchmark JAR. Note that I've only tested this on Linux.
Benchmark results with this code are available at https://metaborg.github.io/jsglr2evaluation-site/2020-12-23%2023:59/index.html. Note that only the results for Java are shown, I still have to fix that bug :upside_down_face:
> TreeSitter benchmark (and some other fixes)

- org.spoofax.interpreter.library.jsglr/src/main/java/org/spoofax/interpreter/library/jsglr/origin/OriginSublistTermPrimitive.java
This bug was discovered when using the `construct-textual-change` strategy, to perform a layout-preserving transformation (renaming). It'ts likely this simply has never been used with a current language project, as the code is like 15 years old.
Here's the strategy that failed before this bugfix:
```    	
rename-action-2 :
(selected-term, _, ast, path, project-path) -> (filename, result)
where
analysis := <nabl2-get-ast-analysis> ast;
<not(nabl2-analysis-has-errors)> analysis
with
new-name := <read-new-name> path
; renamed-ast := <rename(|selected-term, new-name, path)
; filename := <compose-filename> path
; (_, _, result) := <construct-textual-change> (ast, renamed-ast)
```
> Origin Tracking Bugfix

- org.spoofax.jsglr2.benchmark/src/main/java/org/spoofax/jsglr2/benchmark/jsglr2/JSGLR2BenchmarkIncremental.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/ParseException.java
Two small updates that accompany the changes in metaborg/jsglr2evaluation#6. The don't necessarily depend on each other, though :slightly_smiling_face: 
- I've added the Elkhound parser to the incremental benchmarks.
- While debugging the encoding issue described in metaborg/jsglr2evaluation#6, it seemed like a good idea to print the Unicode value of the current character in the message of a `ParseException`. I left this in, who knows when it comes in handy again :stuck_out_tongue: The value is printed as `U+XXXX`, e.g. the letter `J` is `U+004A`.
> Add Elkhound to incremental benchmarks

- org.spoofax.jsglr2.measure/pom.xml
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/CSV.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/Config.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/JSGLR2Measurements.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/JSGLR2MeasurementsIncremental.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/Measurements.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/incremental/IncrementalParserMeasureObserver.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/incremental/IncrementalParsingMeasurement.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/incremental/IncrementalParsingMeasurements.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/parsetable/ParseTableMeasurements.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/parsing/ParserMeasureObserver.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/parsing/ParsingMeasurements.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/parseforest/IncrementalParseNode.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/IParserObserver.java
In order to make the incremental parsing measurements fit in the framework of the existing measurements, I had to add type parameters to several classes, similar to the benchmark classes.
To make things a bit cleaner, I lifted `JSGLR2Measurements.Config` to its own class file.
Besides the incremental parsing measurements, I also made some small changes, which you can find back in the commit log and the diff.
The results of the measurements are displayed on the [evaluation website](https://www.spoofax.dev/jsglr2evaluation-site/2021-03-02%2015:51/index.html) and converted to LaTeX tables in metaborg/jsglr2evaluation#7.
> Incremental Parsing Measurements

- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/BaseTest.java
- org.spoofax.jsglr2.integrationtest/src/test/java/org/spoofax/jsglr2/integrationtest/incremental/IncrementalSGLRThesisExampleTest.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/incremental/IncrementalParsingMeasurement.java
- org.spoofax.jsglr2.measure/src/main/java/org/spoofax/jsglr2/measure/incremental/IncrementalParsingMeasurements.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/incremental/IncrementalParser.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/AbstractIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/AbstractPreprocessingIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/EagerPreprocessingIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/IIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/IncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/IncrementalInputStackFactory.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/LazyPreprocessingIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/LinkedIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/LinkedPreprocessingIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/inputstack/incremental/StringIncrementalInputStack.java
- org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/parser/observing/IParserObserver.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/inputstack/incremental/AbstractPreprocessingIncrementalInputStackTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/inputstack/incremental/IncrementalInputStackTest.java
- org.spoofax.jsglr2/src/test/java/org/spoofax/jsglr2/inputstack/incremental/LinkedIncrementalInputStackTest.java
To be merged together with metaborg/jsglr2evaluation#12.
I already had these commits ready before my graduation, but the evaluation scripts still needed to be cleaned up after that. But this is done now :smile: 
The commits should be reviewable one-by-one. Most changes are in the tests and measurements, with the only real change in the parser itself being the addition of a `breakdownReason` parameter to the `*InputStack.breakDown` method and the reordering of some statements. All in all, no algorithmic changes :slightly_smiling_face:
> ISGLR: The final sync
